default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: <%= ENV['RAILS_DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: GitHub_Actions_test_development

test:
  <<: *default
  database: GitHub_Actions_test_test

production:
  <<: *default
  database: GitHub_Actions_test_production
  username: GitHub_Actions_test
  password: <%= ENV['GITHUB_ACTIONS_TEST_DATABASE_PASSWORD'] %>
