name: RSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test

    container:
      image: ruby:2.6.3
      env:
        RAILS_ENV: test
        POSTGRES_HOST: postgres
        RAILS_DATABASE_USER: postgres
        RAILS_DATABASE_PASSWORD: password

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Bundler
        run: gem install bundler
      
      - name: Yarn Install
        run: |
          npm i -g yarn
          yarn install --frozen-lockfile
      
      - name: Bundle Install
        run: bundle install

      - name: Setup DB
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/GitHub_Actions_test_test

      - name: Run Test
        run: |
          bundle exec rspec
          